-- ===================================================================
-- BEAN BOUTIQUE SEED DATA
-- Initial data for products, events, blog posts, and more
-- ===================================================================
--
-- INSTRUCTIONS:
-- 1. Run MIGRATION.sql first to create all tables
-- 2. Go to Supabase Dashboard > SQL Editor
-- 3. Create a new query
-- 4. Copy and paste this file
-- 5. Click "Run" to seed the database
--
-- ===================================================================

-- ===================
-- COFFEE PRODUCTS
-- ===================
-- Note: UUID is auto-generated by the database, so we don't specify the id column

INSERT INTO public.products (name, description, price, stock, image_url, category, origin, roast_level, flavor_notes, processing_method, altitude, featured, rating, review_count) VALUES
('Ethiopian Yirgacheffe', 'Delicate floral notes with bright citrus undertones and a tea-like body. This washed coffee from the birthplace of coffee offers a truly unique experience.', 16.99, 150, 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800', 'coffee', 'Ethiopia', 'light', ARRAY['floral', 'citrus', 'tea-like'], 'washed', '1700-2200m', true, 4.8, 127),

('Colombian Supremo', 'Rich and full-bodied with notes of chocolate and caramel. This medium roast from the Colombian highlands delivers a perfectly balanced cup.', 15.99, 200, 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800', 'coffee', 'Colombia', 'medium', ARRAY['chocolate', 'caramel', 'nuts'], 'washed', '1200-1800m', true, 4.7, 98),

('Kenya AA', 'Bright and wine-like acidity with berry notes and a full body. This exceptional coffee from Kenya''s high-altitude regions is a true connoisseur''s choice.', 18.99, 120, 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800', 'coffee', 'Kenya', 'medium', ARRAY['berry', 'wine', 'black currant'], 'washed', '1500-2100m', true, 4.9, 142),

('Brazil Santos', 'Smooth and nutty with chocolate notes and low acidity. Perfect for espresso or as an everyday drinking coffee.', 14.99, 180, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', 'coffee', 'Brazil', 'medium', ARRAY['chocolate', 'nuts', 'caramel'], 'natural', '800-1200m', false, 4.6, 76),

('Sumatra Mandheling', 'Earthy and complex with herbal notes and a syrupy body. This dark roast from Indonesia offers a bold, unforgettable taste.', 17.99, 100, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800', 'coffee', 'Indonesia', 'dark', ARRAY['earthy', 'herbal', 'dark chocolate'], 'wet-hulled', '1000-1500m', false, 4.5, 65),

('Guatemala Antigua', 'Balanced and smooth with cocoa and spice notes. This volcanic soil coffee offers remarkable complexity and a clean finish.', 16.49, 140, 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800', 'coffee', 'Guatemala', 'medium', ARRAY['cocoa', 'spice', 'citrus'], 'washed', '1500-1700m', false, 4.7, 88),

('Costa Rica Tarrazú', 'Crisp and bright with honey sweetness and citrus notes. From one of the world''s most prestigious coffee regions.', 17.49, 130, 'https://images.unsplash.com/photo-1501492673258-6d2f8e0b1d88?w=800', 'coffee', 'Costa Rica', 'light', ARRAY['honey', 'citrus', 'apple'], 'washed', '1200-1900m', true, 4.8, 103),

('Nicaragua Matagalpa', 'Smooth and sweet with chocolate and caramel notes. A well-balanced coffee with mild acidity and a creamy body.', 15.49, 160, 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800', 'coffee', 'Nicaragua', 'medium', ARRAY['chocolate', 'caramel', 'orange'], 'washed', '1000-1400m', false, 4.6, 71);

-- ===================
-- BREWING EQUIPMENT
-- ===================
-- Note: UUID is auto-generated by the database, so we don't specify the id column

INSERT INTO public.products (name, description, price, stock, image_url, category, brand, model, type, featured, rating, review_count) VALUES
('Breville Barista Express', 'Professional-grade espresso machine with integrated grinder. Perfect for home baristas who want café-quality espresso.', 599.99, 25, 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800', 'equipment', 'Breville', 'BES870XL', 'Espresso Machine', true, 4.9, 234),

('Chemex Classic 8-Cup', 'Iconic pour-over coffee maker with elegant design. Produces clean, flavorful coffee with a beautiful presentation.', 44.99, 80, 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800', 'equipment', 'Chemex', 'CM-8A', 'Pour Over', true, 4.8, 189),

('Baratza Encore Grinder', 'Entry-level burr grinder with 40 grind settings. Consistent grind quality for any brewing method.', 149.99, 45, 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', 'equipment', 'Baratza', 'Encore', 'Coffee Grinder', true, 4.7, 312),

('Hario V60 Dripper', 'Classic Japanese pour-over dripper. Simple design that allows for excellent extraction control.', 24.99, 120, 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800', 'equipment', 'Hario', 'V60-02', 'Pour Over', false, 4.8, 267),

('Fellow Stagg EKG Kettle', 'Electric pour-over kettle with precision temperature control and sleek design. Variable temperature control for perfect brewing.', 179.99, 35, 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800', 'equipment', 'Fellow', 'Stagg EKG', 'Kettle', true, 4.9, 198),

('AeroPress Go', 'Portable coffee maker perfect for travel. Makes smooth, rich coffee in about a minute.', 39.99, 100, 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800', 'equipment', 'AeroPress', 'Go', 'Portable Brewer', false, 4.7, 156),

('Comandante C40 MK4', 'Premium manual coffee grinder with exceptional grind quality. Perfect for home and travel.', 279.99, 20, 'https://images.unsplash.com/photo-1501492673258-6d2f8e0b1d88?w=800', 'equipment', 'Comandante', 'C40 MK4', 'Manual Grinder', true, 4.9, 142),

('Fellow Ode Brew Grinder', 'Flat burr grinder designed specifically for filter coffee. Beautiful design with professional-grade performance.', 299.99, 28, 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800', 'equipment', 'Fellow', 'Ode Gen 2', 'Electric Grinder', false, 4.8, 178);

-- ===================
-- EVENTS
-- ===================

INSERT INTO public.events (title, description, location, event_date, duration, capacity, enrolled, price, instructor, level, category, image_url, active) VALUES
('Latte Art Workshop', 'Learn to create beautiful latte art designs. Master the basics of milk steaming and pouring techniques to create hearts, rosettas, and more.', 'Bean Boutique Café, Main Street', (now() + interval '15 days')::timestamptz, 120, 12, 8, 45.00, 'Maria Santos', 'beginner', 'workshop', 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800', true),

('Coffee Cupping Session', 'Professional coffee tasting experience. Learn to identify flavor notes, evaluate quality, and understand coffee origins through guided cupping.', 'Bean Boutique Café, Main Street', (now() + interval '8 days')::timestamptz, 90, 15, 12, 35.00, 'James Anderson', 'intermediate', 'cupping', 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800', true),

('Home Espresso Basics', 'Master the art of espresso at home. From grinding to extraction, learn everything you need to make café-quality espresso.', 'Bean Boutique Training Room', (now() + interval '22 days')::timestamptz, 150, 10, 5, 65.00, 'David Chen', 'beginner', 'workshop', 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', true),

('Pour-Over Perfection', 'Elevate your pour-over technique. Explore different brewing methods, ratios, and water temperatures for optimal extraction.', 'Bean Boutique Café, Main Street', (now() + interval '12 days')::timestamptz, 90, 12, 9, 40.00, 'Sarah Williams', 'intermediate', 'workshop', 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800', true),

('Origin Tasting: Ethiopia', 'Explore Ethiopian coffee origins. Taste rare varietals from different regions and learn about Ethiopian coffee culture.', 'Bean Boutique Café, Main Street', (now() + interval '20 days')::timestamptz, 120, 20, 15, 50.00, 'Maria Santos', 'all levels', 'tasting', 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800', true),

('Coffee & Food Pairing', 'Discover perfect coffee and food combinations. Learn the principles of pairing coffee with desserts, breakfast, and savory dishes.', 'Bean Boutique Café, Main Street', (now() + interval '18 days')::timestamptz, 120, 16, 10, 55.00, 'James Anderson', 'all levels', 'tasting', 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800', true);

-- ===================
-- BLOG POSTS
-- ===================

INSERT INTO public.blog_posts (title, content, excerpt, author_name, image_url, category, tags, published, published_at) VALUES
('The Perfect Pour-Over: A Step-by-Step Guide', 'Pour-over coffee brewing is an art form that produces clean, flavorful coffee. Here''s our comprehensive guide to mastering this technique...\n\nStart with freshly roasted beans, preferably within 2-4 weeks of roasting. Use a medium-fine grind, similar to table salt. The water temperature should be between 195-205°F (90-96°C).\n\nThe brewing process involves blooming the coffee first, then pouring in circular motions to ensure even extraction. Total brew time should be 3-4 minutes for optimal results.\n\nKey tips: Use filtered water, maintain consistent pour rate, and experiment with different ratios to find your perfect cup.', 
'Master the art of pour-over brewing with our complete guide. Learn the techniques used by professional baristas.', 
'Maria Santos', 
'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800', 
'brewing', 
ARRAY['brewing', 'pour-over', 'technique'], 
true, 
(now() - interval '5 days')::timestamptz),

('Understanding Coffee Origins: A Journey Through Flavor', 'Coffee grows in the "Bean Belt" around the equator, and each origin offers unique flavor characteristics...\n\nAfrican coffees, particularly from Ethiopia and Kenya, tend to have bright acidity and fruity, wine-like notes. Latin American coffees from Colombia, Guatemala, and Costa Rica offer balanced profiles with chocolate and nut notes. Indonesian coffees are known for earthy, full-bodied characteristics.\n\nThe terroir, processing method, and varietal all contribute to the final cup. Understanding these factors helps you choose coffees that match your preferences.', 
'Explore how geography, climate, and processing methods influence coffee flavor profiles from around the world.', 
'James Anderson', 
'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800', 
'origins', 
ARRAY['origins', 'flavor', 'education'], 
true, 
(now() - interval '10 days')::timestamptz),

('Espresso 101: The Foundation of Coffee Culture', 'Espresso is not a bean or roast level—it''s a brewing method that produces concentrated coffee...\n\nThe key to great espresso is the "four M''s": Macinazione (grind), Miscela (blend), Macchina (machine), and Mano (barista skill). Each element must work in harmony.\n\nProper extraction takes 25-30 seconds and produces about 2 oz of espresso with a thick, golden crema on top. The grind size, dose, and tamping pressure all affect the final shot.\n\nAt home, start with fresh beans, a quality grinder, and practice. Small adjustments make big differences in taste.', 
'Learn the fundamentals of espresso brewing and what makes a perfect shot of espresso.', 
'David Chen', 
'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800', 
'brewing', 
ARRAY['espresso', 'brewing', 'education'], 
true, 
(now() - interval '15 days')::timestamptz),

('Sustainable Coffee: From Farm to Cup', 'Sustainability in coffee means fair compensation for farmers, environmental protection, and long-term viability...\n\nMany coffee farmers struggle with climate change, fluctuating prices, and outdated practices. Buying specialty coffee at fair prices helps farmers invest in quality and sustainability.\n\nLook for certifications like Fair Trade, Rainforest Alliance, and organic labels. Better yet, buy from roasters who have direct relationships with farmers.\n\nAt Bean Boutique, we source our coffees through direct trade relationships, ensuring farmers receive premium prices and invest in sustainable practices.', 
'Discover how your coffee choices impact farmers, communities, and the environment.', 
'Sarah Williams', 
'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', 
'sustainability', 
ARRAY['sustainability', 'ethics', 'education'], 
true, 
(now() - interval '7 days')::timestamptz);

-- ===================
-- OFFERS
-- ===================

INSERT INTO public.offers (product_id, title, description, discount_percent, active, start_date, end_date) VALUES
((SELECT id FROM public.products WHERE name = 'Ethiopian Yirgacheffe'), 
 'New Customer Special', 
 'Get 15% off your first coffee purchase', 
 15.00, 
 true, 
 now()::timestamptz, 
 (now() + interval '30 days')::timestamptz),

((SELECT id FROM public.products WHERE name = 'Breville Barista Express'), 
 'Equipment Sale', 
 'Save 10% on espresso machines this month', 
 10.00, 
 true, 
 now()::timestamptz, 
 (now() + interval '30 days')::timestamptz),

((SELECT id FROM public.products WHERE name = 'Kenya AA'), 
 'Featured Origin', 
 'Discover our featured coffee from Kenya with 10% off', 
 10.00, 
 true, 
 now()::timestamptz, 
 (now() + interval '14 days')::timestamptz);

-- ===================
-- PROMOTIONS
-- ===================

INSERT INTO public.promotions (title, description, code, discount_type, discount_value, start_date, end_date, active, usage_limit) VALUES
('Welcome10', 
 'Welcome! Get 10% off your first order', 
 'WELCOME10', 
 'percentage', 
 10.00, 
 now()::timestamptz, 
 (now() + interval '90 days')::timestamptz, 
 true, 
 NULL),

('FREESHIP50', 
 'Free shipping on orders over $50', 
 'FREESHIP50', 
 'percentage', 
 0.00, 
 now()::timestamptz, 
 (now() + interval '60 days')::timestamptz, 
 true, 
 NULL),

('SUMMERBREW', 
 'Summer Special - $15 off orders over $100', 
 'SUMMERBREW', 
 'fixed', 
 15.00, 
 now()::timestamptz, 
 (now() + interval '45 days')::timestamptz, 
 true, 
 500);

-- ===================
-- BANNERS
-- ===================

INSERT INTO public.banners (image_url, title, subtitle, link, active, sort_order) VALUES
('https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=1600', 
 'Fresh Roasted Coffee', 
 'Discover our selection of single-origin beans', 
 '/coffee', 
 true, 
 1),

('https://images.unsplash.com/photo-1511920170033-f8396924c348?w=1600', 
 'Master Your Craft', 
 'Professional brewing equipment for home baristas', 
 '/equipment', 
 true, 
 2),

('https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=1600', 
 'Join Our Workshops', 
 'Learn from expert baristas in hands-on classes', 
 '/events', 
 true, 
 3);

-- ===================================================================
-- SEED DATA COMPLETE
-- ===================================================================
--
-- Next steps:
-- 1. Create your first admin user through the signup endpoint
-- 2. Update the user's role to 'admin' in the users table
-- 3. Start using the application!
--
-- To make a user an admin:
-- UPDATE public.users SET role = 'admin' WHERE email = 'your-email@example.com';
--
-- ===================================================================